# Run: scafctl run solution -f examples/providers/identity-list.yaml
# Run: scafctl run resolver -f examples/providers/identity-list.yaml

apiVersion: scafctl.io/v1
kind: Solution

metadata:
  name: identity-list-example
  displayName: Identity List Example
  category: providers
  tags:
    - identity
    - provider-example
  description: List available authentication handlers

spec:
  resolvers:
    handlers:
      description: Available auth handlers
      type: any
      resolve:
        with:
          - provider: identity
            inputs:
              operation: list
