version: 2
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/scafctl
    binary: "{{ .ProjectName }}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
          - -w
          - -s
          - -X main.Commit={{.Commit}}
          - -X main.BuildVersion={{.Version}}
          - -X main.BuildTime={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        formats: ['zip']
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    args:
      - "sign-blob"
      - "${artifact}"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "--yes"
sboms:
  - artifacts: archive
homebrew_casks:
  - name: scafctl
    repository:
      owner: oakwood-commons
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/oakwood-commons/scafctl"
    description: "A configuration discovery and scaffolding tool using CEL for dynamic evaluation"
    license: "Apache-2.0"
release:
  draft: false
  prerelease: auto
changelog:
  disable: false
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
    - title: Others
      order: 999
  filters:
    exclude:
      - '^chore:'
