// Code generated by scafctl. DO NOT EDIT.
// Project: myservice
// Author: bob
// Generation #0
// Package myservice provides the main application entry point.
package myservice

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println("myservice starting...")
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	svc := NewService()
	return svc.Start()
}
