// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: pkg/plugin/proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_GetProviders_FullMethodName          = "/plugin.PluginService/GetProviders"
	PluginService_GetProviderDescriptor_FullMethodName = "/plugin.PluginService/GetProviderDescriptor"
	PluginService_ExecuteProvider_FullMethodName       = "/plugin.PluginService/ExecuteProvider"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginService is the main plugin service
type PluginServiceClient interface {
	// GetProviders returns all providers exposed by this plugin
	GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*GetProvidersResponse, error)
	// GetProviderDescriptor returns metadata for a specific provider
	GetProviderDescriptor(ctx context.Context, in *GetProviderDescriptorRequest, opts ...grpc.CallOption) (*GetProviderDescriptorResponse, error)
	// ExecuteProvider executes a provider
	ExecuteProvider(ctx context.Context, in *ExecuteProviderRequest, opts ...grpc.CallOption) (*ExecuteProviderResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*GetProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProvidersResponse)
	err := c.cc.Invoke(ctx, PluginService_GetProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetProviderDescriptor(ctx context.Context, in *GetProviderDescriptorRequest, opts ...grpc.CallOption) (*GetProviderDescriptorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderDescriptorResponse)
	err := c.cc.Invoke(ctx, PluginService_GetProviderDescriptor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) ExecuteProvider(ctx context.Context, in *ExecuteProviderRequest, opts ...grpc.CallOption) (*ExecuteProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteProviderResponse)
	err := c.cc.Invoke(ctx, PluginService_ExecuteProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
//
// PluginService is the main plugin service
type PluginServiceServer interface {
	// GetProviders returns all providers exposed by this plugin
	GetProviders(context.Context, *GetProvidersRequest) (*GetProvidersResponse, error)
	// GetProviderDescriptor returns metadata for a specific provider
	GetProviderDescriptor(context.Context, *GetProviderDescriptorRequest) (*GetProviderDescriptorResponse, error)
	// ExecuteProvider executes a provider
	ExecuteProvider(context.Context, *ExecuteProviderRequest) (*ExecuteProviderResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) GetProviders(context.Context, *GetProvidersRequest) (*GetProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviders not implemented")
}
func (UnimplementedPluginServiceServer) GetProviderDescriptor(context.Context, *GetProviderDescriptorRequest) (*GetProviderDescriptorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderDescriptor not implemented")
}
func (UnimplementedPluginServiceServer) ExecuteProvider(context.Context, *ExecuteProviderRequest) (*ExecuteProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteProvider not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_GetProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetProviders(ctx, req.(*GetProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetProviderDescriptor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderDescriptorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetProviderDescriptor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetProviderDescriptor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetProviderDescriptor(ctx, req.(*GetProviderDescriptorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_ExecuteProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).ExecuteProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_ExecuteProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).ExecuteProvider(ctx, req.(*ExecuteProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProviders",
			Handler:    _PluginService_GetProviders_Handler,
		},
		{
			MethodName: "GetProviderDescriptor",
			Handler:    _PluginService_GetProviderDescriptor_Handler,
		},
		{
			MethodName: "ExecuteProvider",
			Handler:    _PluginService_ExecuteProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/proto/plugin.proto",
}
