// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_GetProviders_FullMethodName          = "/plugin.PluginService/GetProviders"
	PluginService_GetProviderDescriptor_FullMethodName = "/plugin.PluginService/GetProviderDescriptor"
	PluginService_ExecuteProvider_FullMethodName       = "/plugin.PluginService/ExecuteProvider"
	PluginService_DescribeWhatIf_FullMethodName        = "/plugin.PluginService/DescribeWhatIf"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginService is the provider plugin service.
type PluginServiceClient interface {
	// GetProviders returns all providers exposed by this plugin
	GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*GetProvidersResponse, error)
	// GetProviderDescriptor returns metadata for a specific provider
	GetProviderDescriptor(ctx context.Context, in *GetProviderDescriptorRequest, opts ...grpc.CallOption) (*GetProviderDescriptorResponse, error)
	// ExecuteProvider executes a provider
	ExecuteProvider(ctx context.Context, in *ExecuteProviderRequest, opts ...grpc.CallOption) (*ExecuteProviderResponse, error)
	// DescribeWhatIf returns a human-readable description of what the provider
	// would do with the given inputs, without executing.
	DescribeWhatIf(ctx context.Context, in *DescribeWhatIfRequest, opts ...grpc.CallOption) (*DescribeWhatIfResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) GetProviders(ctx context.Context, in *GetProvidersRequest, opts ...grpc.CallOption) (*GetProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProvidersResponse)
	err := c.cc.Invoke(ctx, PluginService_GetProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetProviderDescriptor(ctx context.Context, in *GetProviderDescriptorRequest, opts ...grpc.CallOption) (*GetProviderDescriptorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderDescriptorResponse)
	err := c.cc.Invoke(ctx, PluginService_GetProviderDescriptor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) ExecuteProvider(ctx context.Context, in *ExecuteProviderRequest, opts ...grpc.CallOption) (*ExecuteProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteProviderResponse)
	err := c.cc.Invoke(ctx, PluginService_ExecuteProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) DescribeWhatIf(ctx context.Context, in *DescribeWhatIfRequest, opts ...grpc.CallOption) (*DescribeWhatIfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeWhatIfResponse)
	err := c.cc.Invoke(ctx, PluginService_DescribeWhatIf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
//
// PluginService is the provider plugin service.
type PluginServiceServer interface {
	// GetProviders returns all providers exposed by this plugin
	GetProviders(context.Context, *GetProvidersRequest) (*GetProvidersResponse, error)
	// GetProviderDescriptor returns metadata for a specific provider
	GetProviderDescriptor(context.Context, *GetProviderDescriptorRequest) (*GetProviderDescriptorResponse, error)
	// ExecuteProvider executes a provider
	ExecuteProvider(context.Context, *ExecuteProviderRequest) (*ExecuteProviderResponse, error)
	// DescribeWhatIf returns a human-readable description of what the provider
	// would do with the given inputs, without executing.
	DescribeWhatIf(context.Context, *DescribeWhatIfRequest) (*DescribeWhatIfResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) GetProviders(context.Context, *GetProvidersRequest) (*GetProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviders not implemented")
}
func (UnimplementedPluginServiceServer) GetProviderDescriptor(context.Context, *GetProviderDescriptorRequest) (*GetProviderDescriptorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderDescriptor not implemented")
}
func (UnimplementedPluginServiceServer) ExecuteProvider(context.Context, *ExecuteProviderRequest) (*ExecuteProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteProvider not implemented")
}
func (UnimplementedPluginServiceServer) DescribeWhatIf(context.Context, *DescribeWhatIfRequest) (*DescribeWhatIfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeWhatIf not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_GetProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetProviders(ctx, req.(*GetProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetProviderDescriptor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderDescriptorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetProviderDescriptor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetProviderDescriptor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetProviderDescriptor(ctx, req.(*GetProviderDescriptorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_ExecuteProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).ExecuteProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_ExecuteProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).ExecuteProvider(ctx, req.(*ExecuteProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_DescribeWhatIf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeWhatIfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).DescribeWhatIf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_DescribeWhatIf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).DescribeWhatIf(ctx, req.(*DescribeWhatIfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProviders",
			Handler:    _PluginService_GetProviders_Handler,
		},
		{
			MethodName: "GetProviderDescriptor",
			Handler:    _PluginService_GetProviderDescriptor_Handler,
		},
		{
			MethodName: "ExecuteProvider",
			Handler:    _PluginService_ExecuteProvider_Handler,
		},
		{
			MethodName: "DescribeWhatIf",
			Handler:    _PluginService_DescribeWhatIf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	AuthHandlerService_GetAuthHandlers_FullMethodName    = "/plugin.AuthHandlerService/GetAuthHandlers"
	AuthHandlerService_Login_FullMethodName              = "/plugin.AuthHandlerService/Login"
	AuthHandlerService_Logout_FullMethodName             = "/plugin.AuthHandlerService/Logout"
	AuthHandlerService_GetStatus_FullMethodName          = "/plugin.AuthHandlerService/GetStatus"
	AuthHandlerService_GetToken_FullMethodName           = "/plugin.AuthHandlerService/GetToken"
	AuthHandlerService_ListCachedTokens_FullMethodName   = "/plugin.AuthHandlerService/ListCachedTokens"
	AuthHandlerService_PurgeExpiredTokens_FullMethodName = "/plugin.AuthHandlerService/PurgeExpiredTokens"
)

// AuthHandlerServiceClient is the client API for AuthHandlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthHandlerService is the auth handler plugin service.
type AuthHandlerServiceClient interface {
	// GetAuthHandlers returns metadata for all auth handlers exposed by this plugin.
	GetAuthHandlers(ctx context.Context, in *GetAuthHandlersRequest, opts ...grpc.CallOption) (*GetAuthHandlersResponse, error)
	// Login initiates authentication. Returns a stream: zero or more DeviceCodePrompt
	// messages followed by exactly one LoginResult message.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LoginStreamMessage], error)
	// Logout clears stored credentials for the named handler.
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// GetStatus returns the current authentication status.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// GetToken returns a valid access token.
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
	// ListCachedTokens enumerates cached tokens for the named handler.
	ListCachedTokens(ctx context.Context, in *ListCachedTokensRequest, opts ...grpc.CallOption) (*ListCachedTokensResponse, error)
	// PurgeExpiredTokens removes expired tokens for the named handler.
	PurgeExpiredTokens(ctx context.Context, in *PurgeExpiredTokensRequest, opts ...grpc.CallOption) (*PurgeExpiredTokensResponse, error)
}

type authHandlerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthHandlerServiceClient(cc grpc.ClientConnInterface) AuthHandlerServiceClient {
	return &authHandlerServiceClient{cc}
}

func (c *authHandlerServiceClient) GetAuthHandlers(ctx context.Context, in *GetAuthHandlersRequest, opts ...grpc.CallOption) (*GetAuthHandlersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthHandlersResponse)
	err := c.cc.Invoke(ctx, AuthHandlerService_GetAuthHandlers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authHandlerServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LoginStreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuthHandlerService_ServiceDesc.Streams[0], AuthHandlerService_Login_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LoginRequest, LoginStreamMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthHandlerService_LoginClient = grpc.ServerStreamingClient[LoginStreamMessage]

func (c *authHandlerServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, AuthHandlerService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authHandlerServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, AuthHandlerService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authHandlerServiceClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, AuthHandlerService_GetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authHandlerServiceClient) ListCachedTokens(ctx context.Context, in *ListCachedTokensRequest, opts ...grpc.CallOption) (*ListCachedTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCachedTokensResponse)
	err := c.cc.Invoke(ctx, AuthHandlerService_ListCachedTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authHandlerServiceClient) PurgeExpiredTokens(ctx context.Context, in *PurgeExpiredTokensRequest, opts ...grpc.CallOption) (*PurgeExpiredTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeExpiredTokensResponse)
	err := c.cc.Invoke(ctx, AuthHandlerService_PurgeExpiredTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthHandlerServiceServer is the server API for AuthHandlerService service.
// All implementations must embed UnimplementedAuthHandlerServiceServer
// for forward compatibility.
//
// AuthHandlerService is the auth handler plugin service.
type AuthHandlerServiceServer interface {
	// GetAuthHandlers returns metadata for all auth handlers exposed by this plugin.
	GetAuthHandlers(context.Context, *GetAuthHandlersRequest) (*GetAuthHandlersResponse, error)
	// Login initiates authentication. Returns a stream: zero or more DeviceCodePrompt
	// messages followed by exactly one LoginResult message.
	Login(*LoginRequest, grpc.ServerStreamingServer[LoginStreamMessage]) error
	// Logout clears stored credentials for the named handler.
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// GetStatus returns the current authentication status.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// GetToken returns a valid access token.
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
	// ListCachedTokens enumerates cached tokens for the named handler.
	ListCachedTokens(context.Context, *ListCachedTokensRequest) (*ListCachedTokensResponse, error)
	// PurgeExpiredTokens removes expired tokens for the named handler.
	PurgeExpiredTokens(context.Context, *PurgeExpiredTokensRequest) (*PurgeExpiredTokensResponse, error)
	mustEmbedUnimplementedAuthHandlerServiceServer()
}

// UnimplementedAuthHandlerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthHandlerServiceServer struct{}

func (UnimplementedAuthHandlerServiceServer) GetAuthHandlers(context.Context, *GetAuthHandlersRequest) (*GetAuthHandlersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthHandlers not implemented")
}
func (UnimplementedAuthHandlerServiceServer) Login(*LoginRequest, grpc.ServerStreamingServer[LoginStreamMessage]) error {
	return status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthHandlerServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthHandlerServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAuthHandlerServiceServer) GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedAuthHandlerServiceServer) ListCachedTokens(context.Context, *ListCachedTokensRequest) (*ListCachedTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCachedTokens not implemented")
}
func (UnimplementedAuthHandlerServiceServer) PurgeExpiredTokens(context.Context, *PurgeExpiredTokensRequest) (*PurgeExpiredTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PurgeExpiredTokens not implemented")
}
func (UnimplementedAuthHandlerServiceServer) mustEmbedUnimplementedAuthHandlerServiceServer() {}
func (UnimplementedAuthHandlerServiceServer) testEmbeddedByValue()                            {}

// UnsafeAuthHandlerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthHandlerServiceServer will
// result in compilation errors.
type UnsafeAuthHandlerServiceServer interface {
	mustEmbedUnimplementedAuthHandlerServiceServer()
}

func RegisterAuthHandlerServiceServer(s grpc.ServiceRegistrar, srv AuthHandlerServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthHandlerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthHandlerService_ServiceDesc, srv)
}

func _AuthHandlerService_GetAuthHandlers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthHandlersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServiceServer).GetAuthHandlers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthHandlerService_GetAuthHandlers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServiceServer).GetAuthHandlers(ctx, req.(*GetAuthHandlersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthHandlerService_Login_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoginRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuthHandlerServiceServer).Login(m, &grpc.GenericServerStream[LoginRequest, LoginStreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthHandlerService_LoginServer = grpc.ServerStreamingServer[LoginStreamMessage]

func _AuthHandlerService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthHandlerService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthHandlerService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthHandlerService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthHandlerService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthHandlerService_GetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServiceServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthHandlerService_ListCachedTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCachedTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServiceServer).ListCachedTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthHandlerService_ListCachedTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServiceServer).ListCachedTokens(ctx, req.(*ListCachedTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthHandlerService_PurgeExpiredTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeExpiredTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthHandlerServiceServer).PurgeExpiredTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthHandlerService_PurgeExpiredTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthHandlerServiceServer).PurgeExpiredTokens(ctx, req.(*PurgeExpiredTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthHandlerService_ServiceDesc is the grpc.ServiceDesc for AuthHandlerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthHandlerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.AuthHandlerService",
	HandlerType: (*AuthHandlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthHandlers",
			Handler:    _AuthHandlerService_GetAuthHandlers_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthHandlerService_Logout_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _AuthHandlerService_GetStatus_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _AuthHandlerService_GetToken_Handler,
		},
		{
			MethodName: "ListCachedTokens",
			Handler:    _AuthHandlerService_ListCachedTokens_Handler,
		},
		{
			MethodName: "PurgeExpiredTokens",
			Handler:    _AuthHandlerService_PurgeExpiredTokens_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Login",
			Handler:       _AuthHandlerService_Login_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
