// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProvidersRequest) Reset() {
	*x = GetProvidersRequest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvidersRequest) ProtoMessage() {}

func (x *GetProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvidersRequest.ProtoReflect.Descriptor instead.
func (*GetProvidersRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type GetProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderNames []string               `protobuf:"bytes,1,rep,name=provider_names,json=providerNames,proto3" json:"provider_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProvidersResponse) Reset() {
	*x = GetProvidersResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvidersResponse) ProtoMessage() {}

func (x *GetProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvidersResponse.ProtoReflect.Descriptor instead.
func (*GetProvidersResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetProvidersResponse) GetProviderNames() []string {
	if x != nil {
		return x.ProviderNames
	}
	return nil
}

type GetProviderDescriptorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderDescriptorRequest) Reset() {
	*x = GetProviderDescriptorRequest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderDescriptorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderDescriptorRequest) ProtoMessage() {}

func (x *GetProviderDescriptorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderDescriptorRequest.ProtoReflect.Descriptor instead.
func (*GetProviderDescriptorRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *GetProviderDescriptorRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

type GetProviderDescriptorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptor_   *ProviderDescriptor    `protobuf:"bytes,1,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderDescriptorResponse) Reset() {
	*x = GetProviderDescriptorResponse{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderDescriptorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderDescriptorResponse) ProtoMessage() {}

func (x *GetProviderDescriptorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderDescriptorResponse.ProtoReflect.Descriptor instead.
func (*GetProviderDescriptorResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *GetProviderDescriptorResponse) GetDescriptor_() *ProviderDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

type ProviderDescriptor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName     string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version         string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Category        string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Capabilities    []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Schema          *Schema                `protobuf:"bytes,7,opt,name=schema,proto3" json:"schema,omitempty"`
	OutputSchemas   map[string]*Schema     `protobuf:"bytes,8,rep,name=output_schemas,json=outputSchemas,proto3" json:"output_schemas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key is capability string (from, transform, validation, authentication, action)
	ApiVersion      string                 `protobuf:"bytes,9,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	MockBehavior    string                 `protobuf:"bytes,10,opt,name=mock_behavior,json=mockBehavior,proto3" json:"mock_behavior,omitempty"`
	SensitiveFields []string               `protobuf:"bytes,11,rep,name=sensitive_fields,json=sensitiveFields,proto3" json:"sensitive_fields,omitempty"`
	Tags            []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	Icon            string                 `protobuf:"bytes,13,opt,name=icon,proto3" json:"icon,omitempty"`
	Links           []*Link                `protobuf:"bytes,14,rep,name=links,proto3" json:"links,omitempty"`
	Examples        []*Example             `protobuf:"bytes,15,rep,name=examples,proto3" json:"examples,omitempty"`
	Maintainers     []*Contact             `protobuf:"bytes,16,rep,name=maintainers,proto3" json:"maintainers,omitempty"`
	Deprecated      bool                   `protobuf:"varint,17,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	Beta            bool                   `protobuf:"varint,18,opt,name=beta,proto3" json:"beta,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProviderDescriptor) Reset() {
	*x = ProviderDescriptor{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderDescriptor) ProtoMessage() {}

func (x *ProviderDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderDescriptor.ProtoReflect.Descriptor instead.
func (*ProviderDescriptor) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ProviderDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderDescriptor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProviderDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProviderDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProviderDescriptor) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProviderDescriptor) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProviderDescriptor) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ProviderDescriptor) GetOutputSchemas() map[string]*Schema {
	if x != nil {
		return x.OutputSchemas
	}
	return nil
}

func (x *ProviderDescriptor) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ProviderDescriptor) GetMockBehavior() string {
	if x != nil {
		return x.MockBehavior
	}
	return ""
}

func (x *ProviderDescriptor) GetSensitiveFields() []string {
	if x != nil {
		return x.SensitiveFields
	}
	return nil
}

func (x *ProviderDescriptor) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProviderDescriptor) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ProviderDescriptor) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ProviderDescriptor) GetExamples() []*Example {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *ProviderDescriptor) GetMaintainers() []*Contact {
	if x != nil {
		return x.Maintainers
	}
	return nil
}

func (x *ProviderDescriptor) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *ProviderDescriptor) GetBeta() bool {
	if x != nil {
		return x.Beta
	}
	return false
}

// Link represents a named hyperlink.
type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Link) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Link) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Example represents a usage example for a provider.
type Example struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Yaml          string                 `protobuf:"bytes,3,opt,name=yaml,proto3" json:"yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Example) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Example) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Example) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

// Contact represents maintainer contact information.
type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    map[string]*Parameter  `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *Schema) GetParameters() map[string]*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Parameter struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Required           bool                   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DefaultValue       []byte                 `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"` // JSON-encoded
	Example            string                 `protobuf:"bytes,5,opt,name=example,proto3" json:"example,omitempty"`
	MaxLength          int32                  `protobuf:"varint,6,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	Pattern            string                 `protobuf:"bytes,7,opt,name=pattern,proto3" json:"pattern,omitempty"`
	PatternDescription string                 `protobuf:"bytes,8,opt,name=pattern_description,json=patternDescription,proto3" json:"pattern_description,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *Parameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Parameter) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Parameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Parameter) GetDefaultValue() []byte {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *Parameter) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *Parameter) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *Parameter) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Parameter) GetPatternDescription() string {
	if x != nil {
		return x.PatternDescription
	}
	return ""
}

type ExecuteProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Input         []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`     // JSON-encoded input map
	Context       []byte                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"` // JSON-encoded context data
	DryRun        bool                   `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteProviderRequest) Reset() {
	*x = ExecuteProviderRequest{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProviderRequest) ProtoMessage() {}

func (x *ExecuteProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProviderRequest.ProtoReflect.Descriptor instead.
func (*ExecuteProviderRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteProviderRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ExecuteProviderRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecuteProviderRequest) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ExecuteProviderRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type ExecuteProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"` // JSON-encoded output (ProviderOutput)
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`   // Empty if no error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteProviderResponse) Reset() {
	*x = ExecuteProviderResponse{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProviderResponse) ProtoMessage() {}

func (x *ExecuteProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProviderResponse.ProtoReflect.Descriptor instead.
func (*ExecuteProviderResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteProviderResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecuteProviderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetAuthHandlersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthHandlersRequest) Reset() {
	*x = GetAuthHandlersRequest{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthHandlersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthHandlersRequest) ProtoMessage() {}

func (x *GetAuthHandlersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthHandlersRequest.ProtoReflect.Descriptor instead.
func (*GetAuthHandlersRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

type GetAuthHandlersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handlers      []*AuthHandlerInfo     `protobuf:"bytes,1,rep,name=handlers,proto3" json:"handlers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthHandlersResponse) Reset() {
	*x = GetAuthHandlersResponse{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthHandlersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthHandlersResponse) ProtoMessage() {}

func (x *GetAuthHandlersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthHandlersResponse.ProtoReflect.Descriptor instead.
func (*GetAuthHandlersResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *GetAuthHandlersResponse) GetHandlers() []*AuthHandlerInfo {
	if x != nil {
		return x.Handlers
	}
	return nil
}

type AuthHandlerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Flows         []string               `protobuf:"bytes,3,rep,name=flows,proto3" json:"flows,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthHandlerInfo) Reset() {
	*x = AuthHandlerInfo{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthHandlerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthHandlerInfo) ProtoMessage() {}

func (x *AuthHandlerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthHandlerInfo.ProtoReflect.Descriptor instead.
func (*AuthHandlerInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *AuthHandlerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthHandlerInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AuthHandlerInfo) GetFlows() []string {
	if x != nil {
		return x.Flows
	}
	return nil
}

func (x *AuthHandlerInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type LoginRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HandlerName    string                 `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scopes         []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Flow           string                 `protobuf:"bytes,4,opt,name=flow,proto3" json:"flow,omitempty"`
	TimeoutSeconds int64                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *LoginRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

func (x *LoginRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LoginRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *LoginRequest) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *LoginRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// LoginStreamMessage is sent over the Login server-stream.
// Exactly one of device_code_prompt or result is set per message.
type LoginStreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LoginStreamMessage_DeviceCodePrompt
	//	*LoginStreamMessage_Result
	//	*LoginStreamMessage_Error
	Payload       isLoginStreamMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginStreamMessage) Reset() {
	*x = LoginStreamMessage{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginStreamMessage) ProtoMessage() {}

func (x *LoginStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginStreamMessage.ProtoReflect.Descriptor instead.
func (*LoginStreamMessage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *LoginStreamMessage) GetPayload() isLoginStreamMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LoginStreamMessage) GetDeviceCodePrompt() *DeviceCodePrompt {
	if x != nil {
		if x, ok := x.Payload.(*LoginStreamMessage_DeviceCodePrompt); ok {
			return x.DeviceCodePrompt
		}
	}
	return nil
}

func (x *LoginStreamMessage) GetResult() *LoginResult {
	if x != nil {
		if x, ok := x.Payload.(*LoginStreamMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *LoginStreamMessage) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*LoginStreamMessage_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isLoginStreamMessage_Payload interface {
	isLoginStreamMessage_Payload()
}

type LoginStreamMessage_DeviceCodePrompt struct {
	DeviceCodePrompt *DeviceCodePrompt `protobuf:"bytes,1,opt,name=device_code_prompt,json=deviceCodePrompt,proto3,oneof"`
}

type LoginStreamMessage_Result struct {
	Result *LoginResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type LoginStreamMessage_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*LoginStreamMessage_DeviceCodePrompt) isLoginStreamMessage_Payload() {}

func (*LoginStreamMessage_Result) isLoginStreamMessage_Payload() {}

func (*LoginStreamMessage_Error) isLoginStreamMessage_Payload() {}

type DeviceCodePrompt struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserCode        string                 `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	VerificationUri string                 `protobuf:"bytes,2,opt,name=verification_uri,json=verificationUri,proto3" json:"verification_uri,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeviceCodePrompt) Reset() {
	*x = DeviceCodePrompt{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCodePrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCodePrompt) ProtoMessage() {}

func (x *DeviceCodePrompt) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCodePrompt.ProtoReflect.Descriptor instead.
func (*DeviceCodePrompt) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *DeviceCodePrompt) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *DeviceCodePrompt) GetVerificationUri() string {
	if x != nil {
		return x.VerificationUri
	}
	return ""
}

func (x *DeviceCodePrompt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoginResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        *Claims                `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,2,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"` // Unix timestamp (seconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResult) Reset() {
	*x = LoginResult{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResult) ProtoMessage() {}

func (x *LoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResult.ProtoReflect.Descriptor instead.
func (*LoginResult) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *LoginResult) GetClaims() *Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *LoginResult) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type Claims struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ObjectId      string                 `protobuf:"bytes,4,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	IssuedAtUnix  int64                  `protobuf:"varint,9,opt,name=issued_at_unix,json=issuedAtUnix,proto3" json:"issued_at_unix,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,10,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claims) Reset() {
	*x = Claims{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claims) ProtoMessage() {}

func (x *Claims) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claims.ProtoReflect.Descriptor instead.
func (*Claims) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *Claims) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Claims) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Claims) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Claims) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *Claims) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Claims) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Claims) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Claims) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Claims) GetIssuedAtUnix() int64 {
	if x != nil {
		return x.IssuedAtUnix
	}
	return 0
}

func (x *Claims) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandlerName   string                 `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *LogoutRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandlerName   string                 `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *GetStatusRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

type GetStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Authenticated   bool                   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	Claims          *Claims                `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	ExpiresAtUnix   int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	LastRefreshUnix int64                  `protobuf:"varint,4,opt,name=last_refresh_unix,json=lastRefreshUnix,proto3" json:"last_refresh_unix,omitempty"`
	TenantId        string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IdentityType    string                 `protobuf:"bytes,6,opt,name=identity_type,json=identityType,proto3" json:"identity_type,omitempty"`
	ClientId        string                 `protobuf:"bytes,7,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TokenFile       string                 `protobuf:"bytes,8,opt,name=token_file,json=tokenFile,proto3" json:"token_file,omitempty"`
	Scopes          []string               `protobuf:"bytes,9,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *GetStatusResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *GetStatusResponse) GetClaims() *Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *GetStatusResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *GetStatusResponse) GetLastRefreshUnix() int64 {
	if x != nil {
		return x.LastRefreshUnix
	}
	return 0
}

func (x *GetStatusResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetStatusResponse) GetIdentityType() string {
	if x != nil {
		return x.IdentityType
	}
	return ""
}

func (x *GetStatusResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetStatusResponse) GetTokenFile() string {
	if x != nil {
		return x.TokenFile
	}
	return ""
}

func (x *GetStatusResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type GetTokenRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HandlerName        string                 `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	Scope              string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	MinValidForSeconds int64                  `protobuf:"varint,3,opt,name=min_valid_for_seconds,json=minValidForSeconds,proto3" json:"min_valid_for_seconds,omitempty"`
	ForceRefresh       bool                   `protobuf:"varint,4,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *GetTokenRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

func (x *GetTokenRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetTokenRequest) GetMinValidForSeconds() int64 {
	if x != nil {
		return x.MinValidForSeconds
	}
	return 0
}

func (x *GetTokenRequest) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

type GetTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	CachedAtUnix  int64                  `protobuf:"varint,5,opt,name=cached_at_unix,json=cachedAtUnix,proto3" json:"cached_at_unix,omitempty"`
	Flow          string                 `protobuf:"bytes,6,opt,name=flow,proto3" json:"flow,omitempty"`
	SessionId     string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *GetTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *GetTokenResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *GetTokenResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetTokenResponse) GetCachedAtUnix() int64 {
	if x != nil {
		return x.CachedAtUnix
	}
	return 0
}

func (x *GetTokenResponse) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *GetTokenResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListCachedTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandlerName   string                 `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCachedTokensRequest) Reset() {
	*x = ListCachedTokensRequest{}
	mi := &file_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCachedTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCachedTokensRequest) ProtoMessage() {}

func (x *ListCachedTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCachedTokensRequest.ProtoReflect.Descriptor instead.
func (*ListCachedTokensRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *ListCachedTokensRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

type ListCachedTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*CachedTokenInfo     `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCachedTokensResponse) Reset() {
	*x = ListCachedTokensResponse{}
	mi := &file_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCachedTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCachedTokensResponse) ProtoMessage() {}

func (x *ListCachedTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCachedTokensResponse.ProtoReflect.Descriptor instead.
func (*ListCachedTokensResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *ListCachedTokensResponse) GetTokens() []*CachedTokenInfo {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type CachedTokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handler       string                 `protobuf:"bytes,1,opt,name=handler,proto3" json:"handler,omitempty"`
	TokenKind     string                 `protobuf:"bytes,2,opt,name=token_kind,json=tokenKind,proto3" json:"token_kind,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Flow          string                 `protobuf:"bytes,5,opt,name=flow,proto3" json:"flow,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,6,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	CachedAtUnix  int64                  `protobuf:"varint,7,opt,name=cached_at_unix,json=cachedAtUnix,proto3" json:"cached_at_unix,omitempty"`
	IsExpired     bool                   `protobuf:"varint,8,opt,name=is_expired,json=isExpired,proto3" json:"is_expired,omitempty"`
	SessionId     string                 `protobuf:"bytes,9,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CachedTokenInfo) Reset() {
	*x = CachedTokenInfo{}
	mi := &file_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedTokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedTokenInfo) ProtoMessage() {}

func (x *CachedTokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedTokenInfo.ProtoReflect.Descriptor instead.
func (*CachedTokenInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *CachedTokenInfo) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *CachedTokenInfo) GetTokenKind() string {
	if x != nil {
		return x.TokenKind
	}
	return ""
}

func (x *CachedTokenInfo) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CachedTokenInfo) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *CachedTokenInfo) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *CachedTokenInfo) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *CachedTokenInfo) GetCachedAtUnix() int64 {
	if x != nil {
		return x.CachedAtUnix
	}
	return 0
}

func (x *CachedTokenInfo) GetIsExpired() bool {
	if x != nil {
		return x.IsExpired
	}
	return false
}

func (x *CachedTokenInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PurgeExpiredTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandlerName   string                 `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeExpiredTokensRequest) Reset() {
	*x = PurgeExpiredTokensRequest{}
	mi := &file_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeExpiredTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeExpiredTokensRequest) ProtoMessage() {}

func (x *PurgeExpiredTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeExpiredTokensRequest.ProtoReflect.Descriptor instead.
func (*PurgeExpiredTokensRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *PurgeExpiredTokensRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

type PurgeExpiredTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurgedCount   int32                  `protobuf:"varint,1,opt,name=purged_count,json=purgedCount,proto3" json:"purged_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeExpiredTokensResponse) Reset() {
	*x = PurgeExpiredTokensResponse{}
	mi := &file_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeExpiredTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeExpiredTokensResponse) ProtoMessage() {}

func (x *PurgeExpiredTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeExpiredTokensResponse.ProtoReflect.Descriptor instead.
func (*PurgeExpiredTokensResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{30}
}

func (x *PurgeExpiredTokensResponse) GetPurgedCount() int32 {
	if x != nil {
		return x.PurgedCount
	}
	return 0
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x06plugin\"\x15\n" +
	"\x13GetProvidersRequest\"=\n" +
	"\x14GetProvidersResponse\x12%\n" +
	"\x0eprovider_names\x18\x01 \x03(\tR\rproviderNames\"C\n" +
	"\x1cGetProviderDescriptorRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\"[\n" +
	"\x1dGetProviderDescriptorResponse\x12:\n" +
	"\n" +
	"descriptor\x18\x01 \x01(\v2\x1a.plugin.ProviderDescriptorR\n" +
	"descriptor\"\xe8\x05\n" +
	"\x12ProviderDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12&\n" +
	"\x06schema\x18\a \x01(\v2\x0e.plugin.SchemaR\x06schema\x12T\n" +
	"\x0eoutput_schemas\x18\b \x03(\v2-.plugin.ProviderDescriptor.OutputSchemasEntryR\routputSchemas\x12\x1f\n" +
	"\vapi_version\x18\t \x01(\tR\n" +
	"apiVersion\x12#\n" +
	"\rmock_behavior\x18\n" +
	" \x01(\tR\fmockBehavior\x12)\n" +
	"\x10sensitive_fields\x18\v \x03(\tR\x0fsensitiveFields\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12\x12\n" +
	"\x04icon\x18\r \x01(\tR\x04icon\x12\"\n" +
	"\x05links\x18\x0e \x03(\v2\f.plugin.LinkR\x05links\x12+\n" +
	"\bexamples\x18\x0f \x03(\v2\x0f.plugin.ExampleR\bexamples\x121\n" +
	"\vmaintainers\x18\x10 \x03(\v2\x0f.plugin.ContactR\vmaintainers\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x11 \x01(\bR\n" +
	"deprecated\x12\x12\n" +
	"\x04beta\x18\x12 \x01(\bR\x04beta\x1aP\n" +
	"\x12OutputSchemasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.plugin.SchemaR\x05value:\x028\x01\",\n" +
	"\x04Link\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"S\n" +
	"\aExample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04yaml\x18\x03 \x01(\tR\x04yaml\"3\n" +
	"\aContact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\x9a\x01\n" +
	"\x06Schema\x12>\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2\x1e.plugin.Schema.ParametersEntryR\n" +
	"parameters\x1aP\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.plugin.ParameterR\x05value:\x028\x01\"\x86\x02\n" +
	"\tParameter\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\fR\fdefaultValue\x12\x18\n" +
	"\aexample\x18\x05 \x01(\tR\aexample\x12\x1d\n" +
	"\n" +
	"max_length\x18\x06 \x01(\x05R\tmaxLength\x12\x18\n" +
	"\apattern\x18\a \x01(\tR\apattern\x12/\n" +
	"\x13pattern_description\x18\b \x01(\tR\x12patternDescription\"\x86\x01\n" +
	"\x16ExecuteProviderRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\x12\x18\n" +
	"\acontext\x18\x03 \x01(\fR\acontext\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\"G\n" +
	"\x17ExecuteProviderResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x18\n" +
	"\x16GetAuthHandlersRequest\"N\n" +
	"\x17GetAuthHandlersResponse\x123\n" +
	"\bhandlers\x18\x01 \x03(\v2\x17.plugin.AuthHandlerInfoR\bhandlers\"\x82\x01\n" +
	"\x0fAuthHandlerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05flows\x18\x03 \x03(\tR\x05flows\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"\xa3\x01\n" +
	"\fLoginRequest\x12!\n" +
	"\fhandler_name\x18\x01 \x01(\tR\vhandlerName\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x12\x12\n" +
	"\x04flow\x18\x04 \x01(\tR\x04flow\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x03R\x0etimeoutSeconds\"\xb0\x01\n" +
	"\x12LoginStreamMessage\x12H\n" +
	"\x12device_code_prompt\x18\x01 \x01(\v2\x18.plugin.DeviceCodePromptH\x00R\x10deviceCodePrompt\x12-\n" +
	"\x06result\x18\x02 \x01(\v2\x13.plugin.LoginResultH\x00R\x06result\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\t\n" +
	"\apayload\"t\n" +
	"\x10DeviceCodePrompt\x12\x1b\n" +
	"\tuser_code\x18\x01 \x01(\tR\buserCode\x12)\n" +
	"\x10verification_uri\x18\x02 \x01(\tR\x0fverificationUri\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"]\n" +
	"\vLoginResult\x12&\n" +
	"\x06claims\x18\x01 \x01(\v2\x0e.plugin.ClaimsR\x06claims\x12&\n" +
	"\x0fexpires_at_unix\x18\x02 \x01(\x03R\rexpiresAtUnix\"\xa5\x02\n" +
	"\x06Claims\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1b\n" +
	"\tobject_id\x18\x04 \x01(\tR\bobjectId\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12$\n" +
	"\x0eissued_at_unix\x18\t \x01(\x03R\fissuedAtUnix\x12&\n" +
	"\x0fexpires_at_unix\x18\n" +
	" \x01(\x03R\rexpiresAtUnix\"2\n" +
	"\rLogoutRequest\x12!\n" +
	"\fhandler_name\x18\x01 \x01(\tR\vhandlerName\"\x10\n" +
	"\x0eLogoutResponse\"5\n" +
	"\x10GetStatusRequest\x12!\n" +
	"\fhandler_name\x18\x01 \x01(\tR\vhandlerName\"\xcb\x02\n" +
	"\x11GetStatusResponse\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated\x12&\n" +
	"\x06claims\x18\x02 \x01(\v2\x0e.plugin.ClaimsR\x06claims\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\x12*\n" +
	"\x11last_refresh_unix\x18\x04 \x01(\x03R\x0flastRefreshUnix\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12#\n" +
	"\ridentity_type\x18\x06 \x01(\tR\fidentityType\x12\x1b\n" +
	"\tclient_id\x18\a \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"token_file\x18\b \x01(\tR\ttokenFile\x12\x16\n" +
	"\x06scopes\x18\t \x03(\tR\x06scopes\"\xa2\x01\n" +
	"\x0fGetTokenRequest\x12!\n" +
	"\fhandler_name\x18\x01 \x01(\tR\vhandlerName\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x121\n" +
	"\x15min_valid_for_seconds\x18\x03 \x01(\x03R\x12minValidForSeconds\x12#\n" +
	"\rforce_refresh\x18\x04 \x01(\bR\fforceRefresh\"\xeb\x01\n" +
	"\x10GetTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12$\n" +
	"\x0ecached_at_unix\x18\x05 \x01(\x03R\fcachedAtUnix\x12\x12\n" +
	"\x04flow\x18\x06 \x01(\tR\x04flow\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\"<\n" +
	"\x17ListCachedTokensRequest\x12!\n" +
	"\fhandler_name\x18\x01 \x01(\tR\vhandlerName\"K\n" +
	"\x18ListCachedTokensResponse\x12/\n" +
	"\x06tokens\x18\x01 \x03(\v2\x17.plugin.CachedTokenInfoR\x06tokens\"\x9f\x02\n" +
	"\x0fCachedTokenInfo\x12\x18\n" +
	"\ahandler\x18\x01 \x01(\tR\ahandler\x12\x1d\n" +
	"\n" +
	"token_kind\x18\x02 \x01(\tR\ttokenKind\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12\x12\n" +
	"\x04flow\x18\x05 \x01(\tR\x04flow\x12&\n" +
	"\x0fexpires_at_unix\x18\x06 \x01(\x03R\rexpiresAtUnix\x12$\n" +
	"\x0ecached_at_unix\x18\a \x01(\x03R\fcachedAtUnix\x12\x1d\n" +
	"\n" +
	"is_expired\x18\b \x01(\bR\tisExpired\x12\x1d\n" +
	"\n" +
	"session_id\x18\t \x01(\tR\tsessionId\">\n" +
	"\x19PurgeExpiredTokensRequest\x12!\n" +
	"\fhandler_name\x18\x01 \x01(\tR\vhandlerName\"?\n" +
	"\x1aPurgeExpiredTokensResponse\x12!\n" +
	"\fpurged_count\x18\x01 \x01(\x05R\vpurgedCount2\x94\x02\n" +
	"\rPluginService\x12I\n" +
	"\fGetProviders\x12\x1b.plugin.GetProvidersRequest\x1a\x1c.plugin.GetProvidersResponse\x12d\n" +
	"\x15GetProviderDescriptor\x12$.plugin.GetProviderDescriptorRequest\x1a%.plugin.GetProviderDescriptorResponse\x12R\n" +
	"\x0fExecuteProvider\x12\x1e.plugin.ExecuteProviderRequest\x1a\x1f.plugin.ExecuteProviderResponse2\x93\x04\n" +
	"\x12AuthHandlerService\x12R\n" +
	"\x0fGetAuthHandlers\x12\x1e.plugin.GetAuthHandlersRequest\x1a\x1f.plugin.GetAuthHandlersResponse\x12;\n" +
	"\x05Login\x12\x14.plugin.LoginRequest\x1a\x1a.plugin.LoginStreamMessage0\x01\x127\n" +
	"\x06Logout\x12\x15.plugin.LogoutRequest\x1a\x16.plugin.LogoutResponse\x12@\n" +
	"\tGetStatus\x12\x18.plugin.GetStatusRequest\x1a\x19.plugin.GetStatusResponse\x12=\n" +
	"\bGetToken\x12\x17.plugin.GetTokenRequest\x1a\x18.plugin.GetTokenResponse\x12U\n" +
	"\x10ListCachedTokens\x12\x1f.plugin.ListCachedTokensRequest\x1a .plugin.ListCachedTokensResponse\x12[\n" +
	"\x12PurgeExpiredTokens\x12!.plugin.PurgeExpiredTokensRequest\x1a\".plugin.PurgeExpiredTokensResponseB5Z3github.com/oakwood-commons/scafctl/pkg/plugin/protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_plugin_proto_goTypes = []any{
	(*GetProvidersRequest)(nil),           // 0: plugin.GetProvidersRequest
	(*GetProvidersResponse)(nil),          // 1: plugin.GetProvidersResponse
	(*GetProviderDescriptorRequest)(nil),  // 2: plugin.GetProviderDescriptorRequest
	(*GetProviderDescriptorResponse)(nil), // 3: plugin.GetProviderDescriptorResponse
	(*ProviderDescriptor)(nil),            // 4: plugin.ProviderDescriptor
	(*Link)(nil),                          // 5: plugin.Link
	(*Example)(nil),                       // 6: plugin.Example
	(*Contact)(nil),                       // 7: plugin.Contact
	(*Schema)(nil),                        // 8: plugin.Schema
	(*Parameter)(nil),                     // 9: plugin.Parameter
	(*ExecuteProviderRequest)(nil),        // 10: plugin.ExecuteProviderRequest
	(*ExecuteProviderResponse)(nil),       // 11: plugin.ExecuteProviderResponse
	(*GetAuthHandlersRequest)(nil),        // 12: plugin.GetAuthHandlersRequest
	(*GetAuthHandlersResponse)(nil),       // 13: plugin.GetAuthHandlersResponse
	(*AuthHandlerInfo)(nil),               // 14: plugin.AuthHandlerInfo
	(*LoginRequest)(nil),                  // 15: plugin.LoginRequest
	(*LoginStreamMessage)(nil),            // 16: plugin.LoginStreamMessage
	(*DeviceCodePrompt)(nil),              // 17: plugin.DeviceCodePrompt
	(*LoginResult)(nil),                   // 18: plugin.LoginResult
	(*Claims)(nil),                        // 19: plugin.Claims
	(*LogoutRequest)(nil),                 // 20: plugin.LogoutRequest
	(*LogoutResponse)(nil),                // 21: plugin.LogoutResponse
	(*GetStatusRequest)(nil),              // 22: plugin.GetStatusRequest
	(*GetStatusResponse)(nil),             // 23: plugin.GetStatusResponse
	(*GetTokenRequest)(nil),               // 24: plugin.GetTokenRequest
	(*GetTokenResponse)(nil),              // 25: plugin.GetTokenResponse
	(*ListCachedTokensRequest)(nil),       // 26: plugin.ListCachedTokensRequest
	(*ListCachedTokensResponse)(nil),      // 27: plugin.ListCachedTokensResponse
	(*CachedTokenInfo)(nil),               // 28: plugin.CachedTokenInfo
	(*PurgeExpiredTokensRequest)(nil),     // 29: plugin.PurgeExpiredTokensRequest
	(*PurgeExpiredTokensResponse)(nil),    // 30: plugin.PurgeExpiredTokensResponse
	nil,                                   // 31: plugin.ProviderDescriptor.OutputSchemasEntry
	nil,                                   // 32: plugin.Schema.ParametersEntry
}
var file_plugin_proto_depIdxs = []int32{
	4,  // 0: plugin.GetProviderDescriptorResponse.descriptor:type_name -> plugin.ProviderDescriptor
	8,  // 1: plugin.ProviderDescriptor.schema:type_name -> plugin.Schema
	31, // 2: plugin.ProviderDescriptor.output_schemas:type_name -> plugin.ProviderDescriptor.OutputSchemasEntry
	5,  // 3: plugin.ProviderDescriptor.links:type_name -> plugin.Link
	6,  // 4: plugin.ProviderDescriptor.examples:type_name -> plugin.Example
	7,  // 5: plugin.ProviderDescriptor.maintainers:type_name -> plugin.Contact
	32, // 6: plugin.Schema.parameters:type_name -> plugin.Schema.ParametersEntry
	14, // 7: plugin.GetAuthHandlersResponse.handlers:type_name -> plugin.AuthHandlerInfo
	17, // 8: plugin.LoginStreamMessage.device_code_prompt:type_name -> plugin.DeviceCodePrompt
	18, // 9: plugin.LoginStreamMessage.result:type_name -> plugin.LoginResult
	19, // 10: plugin.LoginResult.claims:type_name -> plugin.Claims
	19, // 11: plugin.GetStatusResponse.claims:type_name -> plugin.Claims
	28, // 12: plugin.ListCachedTokensResponse.tokens:type_name -> plugin.CachedTokenInfo
	8,  // 13: plugin.ProviderDescriptor.OutputSchemasEntry.value:type_name -> plugin.Schema
	9,  // 14: plugin.Schema.ParametersEntry.value:type_name -> plugin.Parameter
	0,  // 15: plugin.PluginService.GetProviders:input_type -> plugin.GetProvidersRequest
	2,  // 16: plugin.PluginService.GetProviderDescriptor:input_type -> plugin.GetProviderDescriptorRequest
	10, // 17: plugin.PluginService.ExecuteProvider:input_type -> plugin.ExecuteProviderRequest
	12, // 18: plugin.AuthHandlerService.GetAuthHandlers:input_type -> plugin.GetAuthHandlersRequest
	15, // 19: plugin.AuthHandlerService.Login:input_type -> plugin.LoginRequest
	20, // 20: plugin.AuthHandlerService.Logout:input_type -> plugin.LogoutRequest
	22, // 21: plugin.AuthHandlerService.GetStatus:input_type -> plugin.GetStatusRequest
	24, // 22: plugin.AuthHandlerService.GetToken:input_type -> plugin.GetTokenRequest
	26, // 23: plugin.AuthHandlerService.ListCachedTokens:input_type -> plugin.ListCachedTokensRequest
	29, // 24: plugin.AuthHandlerService.PurgeExpiredTokens:input_type -> plugin.PurgeExpiredTokensRequest
	1,  // 25: plugin.PluginService.GetProviders:output_type -> plugin.GetProvidersResponse
	3,  // 26: plugin.PluginService.GetProviderDescriptor:output_type -> plugin.GetProviderDescriptorResponse
	11, // 27: plugin.PluginService.ExecuteProvider:output_type -> plugin.ExecuteProviderResponse
	13, // 28: plugin.AuthHandlerService.GetAuthHandlers:output_type -> plugin.GetAuthHandlersResponse
	16, // 29: plugin.AuthHandlerService.Login:output_type -> plugin.LoginStreamMessage
	21, // 30: plugin.AuthHandlerService.Logout:output_type -> plugin.LogoutResponse
	23, // 31: plugin.AuthHandlerService.GetStatus:output_type -> plugin.GetStatusResponse
	25, // 32: plugin.AuthHandlerService.GetToken:output_type -> plugin.GetTokenResponse
	27, // 33: plugin.AuthHandlerService.ListCachedTokens:output_type -> plugin.ListCachedTokensResponse
	30, // 34: plugin.AuthHandlerService.PurgeExpiredTokens:output_type -> plugin.PurgeExpiredTokensResponse
	25, // [25:35] is the sub-list for method output_type
	15, // [15:25] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_plugin_proto_msgTypes[16].OneofWrappers = []any{
		(*LoginStreamMessage_DeviceCodePrompt)(nil),
		(*LoginStreamMessage_Result)(nil),
		(*LoginStreamMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
