// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/plugin/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProvidersRequest) Reset() {
	*x = GetProvidersRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvidersRequest) ProtoMessage() {}

func (x *GetProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvidersRequest.ProtoReflect.Descriptor instead.
func (*GetProvidersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type GetProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderNames []string               `protobuf:"bytes,1,rep,name=provider_names,json=providerNames,proto3" json:"provider_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProvidersResponse) Reset() {
	*x = GetProvidersResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvidersResponse) ProtoMessage() {}

func (x *GetProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvidersResponse.ProtoReflect.Descriptor instead.
func (*GetProvidersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetProvidersResponse) GetProviderNames() []string {
	if x != nil {
		return x.ProviderNames
	}
	return nil
}

type GetProviderDescriptorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderDescriptorRequest) Reset() {
	*x = GetProviderDescriptorRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderDescriptorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderDescriptorRequest) ProtoMessage() {}

func (x *GetProviderDescriptorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderDescriptorRequest.ProtoReflect.Descriptor instead.
func (*GetProviderDescriptorRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *GetProviderDescriptorRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

type GetProviderDescriptorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptor_   *ProviderDescriptor    `protobuf:"bytes,1,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderDescriptorResponse) Reset() {
	*x = GetProviderDescriptorResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderDescriptorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderDescriptorResponse) ProtoMessage() {}

func (x *GetProviderDescriptorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderDescriptorResponse.ProtoReflect.Descriptor instead.
func (*GetProviderDescriptorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *GetProviderDescriptorResponse) GetDescriptor_() *ProviderDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

type ProviderDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Schema        *Schema                `protobuf:"bytes,7,opt,name=schema,proto3" json:"schema,omitempty"`
	OutputSchemas map[string]*Schema     `protobuf:"bytes,8,rep,name=output_schemas,json=outputSchemas,proto3" json:"output_schemas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key is capability string (from, transform, validation, authentication, action)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderDescriptor) Reset() {
	*x = ProviderDescriptor{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderDescriptor) ProtoMessage() {}

func (x *ProviderDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderDescriptor.ProtoReflect.Descriptor instead.
func (*ProviderDescriptor) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ProviderDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderDescriptor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProviderDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProviderDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProviderDescriptor) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProviderDescriptor) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProviderDescriptor) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ProviderDescriptor) GetOutputSchemas() map[string]*Schema {
	if x != nil {
		return x.OutputSchemas
	}
	return nil
}

type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    map[string]*Parameter  `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Schema) GetParameters() map[string]*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Parameter struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Required           bool                   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DefaultValue       []byte                 `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"` // JSON-encoded
	Example            string                 `protobuf:"bytes,5,opt,name=example,proto3" json:"example,omitempty"`
	MaxLength          int32                  `protobuf:"varint,6,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	Pattern            string                 `protobuf:"bytes,7,opt,name=pattern,proto3" json:"pattern,omitempty"`
	PatternDescription string                 `protobuf:"bytes,8,opt,name=pattern_description,json=patternDescription,proto3" json:"pattern_description,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Parameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Parameter) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Parameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Parameter) GetDefaultValue() []byte {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *Parameter) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *Parameter) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *Parameter) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Parameter) GetPatternDescription() string {
	if x != nil {
		return x.PatternDescription
	}
	return ""
}

type ExecuteProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Input         []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`     // JSON-encoded input map
	Context       []byte                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"` // JSON-encoded context data
	DryRun        bool                   `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteProviderRequest) Reset() {
	*x = ExecuteProviderRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProviderRequest) ProtoMessage() {}

func (x *ExecuteProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProviderRequest.ProtoReflect.Descriptor instead.
func (*ExecuteProviderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteProviderRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ExecuteProviderRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecuteProviderRequest) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ExecuteProviderRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type ExecuteProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"` // JSON-encoded output (ProviderOutput)
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`   // Empty if no error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteProviderResponse) Reset() {
	*x = ExecuteProviderResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProviderResponse) ProtoMessage() {}

func (x *ExecuteProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProviderResponse.ProtoReflect.Descriptor instead.
func (*ExecuteProviderResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteProviderResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecuteProviderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_plugin_proto_plugin_proto protoreflect.FileDescriptor

const file_pkg_plugin_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/plugin/proto/plugin.proto\x12\x06plugin\"\x15\n" +
	"\x13GetProvidersRequest\"=\n" +
	"\x14GetProvidersResponse\x12%\n" +
	"\x0eprovider_names\x18\x01 \x03(\tR\rproviderNames\"C\n" +
	"\x1cGetProviderDescriptorRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\"[\n" +
	"\x1dGetProviderDescriptorResponse\x12:\n" +
	"\n" +
	"descriptor\x18\x01 \x01(\v2\x1a.plugin.ProviderDescriptorR\n" +
	"descriptor\"\x97\x03\n" +
	"\x12ProviderDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12&\n" +
	"\x06schema\x18\a \x01(\v2\x0e.plugin.SchemaR\x06schema\x12T\n" +
	"\x0eoutput_schemas\x18\b \x03(\v2-.plugin.ProviderDescriptor.OutputSchemasEntryR\routputSchemas\x1aP\n" +
	"\x12OutputSchemasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.plugin.SchemaR\x05value:\x028\x01\"\x9a\x01\n" +
	"\x06Schema\x12>\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2\x1e.plugin.Schema.ParametersEntryR\n" +
	"parameters\x1aP\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.plugin.ParameterR\x05value:\x028\x01\"\x86\x02\n" +
	"\tParameter\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\fR\fdefaultValue\x12\x18\n" +
	"\aexample\x18\x05 \x01(\tR\aexample\x12\x1d\n" +
	"\n" +
	"max_length\x18\x06 \x01(\x05R\tmaxLength\x12\x18\n" +
	"\apattern\x18\a \x01(\tR\apattern\x12/\n" +
	"\x13pattern_description\x18\b \x01(\tR\x12patternDescription\"\x86\x01\n" +
	"\x16ExecuteProviderRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\x12\x18\n" +
	"\acontext\x18\x03 \x01(\fR\acontext\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\"G\n" +
	"\x17ExecuteProviderResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x94\x02\n" +
	"\rPluginService\x12I\n" +
	"\fGetProviders\x12\x1b.plugin.GetProvidersRequest\x1a\x1c.plugin.GetProvidersResponse\x12d\n" +
	"\x15GetProviderDescriptor\x12$.plugin.GetProviderDescriptorRequest\x1a%.plugin.GetProviderDescriptorResponse\x12R\n" +
	"\x0fExecuteProvider\x12\x1e.plugin.ExecuteProviderRequest\x1a\x1f.plugin.ExecuteProviderResponseB5Z3github.com/oakwood-commons/scafctl/pkg/plugin/protob\x06proto3"

var (
	file_pkg_plugin_proto_plugin_proto_rawDescOnce sync.Once
	file_pkg_plugin_proto_plugin_proto_rawDescData []byte
)

func file_pkg_plugin_proto_plugin_proto_rawDescGZIP() []byte {
	file_pkg_plugin_proto_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_plugin_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_proto_rawDesc), len(file_pkg_plugin_proto_plugin_proto_rawDesc)))
	})
	return file_pkg_plugin_proto_plugin_proto_rawDescData
}

var file_pkg_plugin_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_plugin_proto_plugin_proto_goTypes = []any{
	(*GetProvidersRequest)(nil),           // 0: plugin.GetProvidersRequest
	(*GetProvidersResponse)(nil),          // 1: plugin.GetProvidersResponse
	(*GetProviderDescriptorRequest)(nil),  // 2: plugin.GetProviderDescriptorRequest
	(*GetProviderDescriptorResponse)(nil), // 3: plugin.GetProviderDescriptorResponse
	(*ProviderDescriptor)(nil),            // 4: plugin.ProviderDescriptor
	(*Schema)(nil),                        // 5: plugin.Schema
	(*Parameter)(nil),                     // 6: plugin.Parameter
	(*ExecuteProviderRequest)(nil),        // 7: plugin.ExecuteProviderRequest
	(*ExecuteProviderResponse)(nil),       // 8: plugin.ExecuteProviderResponse
	nil,                                   // 9: plugin.ProviderDescriptor.OutputSchemasEntry
	nil,                                   // 10: plugin.Schema.ParametersEntry
}
var file_pkg_plugin_proto_plugin_proto_depIdxs = []int32{
	4,  // 0: plugin.GetProviderDescriptorResponse.descriptor:type_name -> plugin.ProviderDescriptor
	5,  // 1: plugin.ProviderDescriptor.schema:type_name -> plugin.Schema
	9,  // 2: plugin.ProviderDescriptor.output_schemas:type_name -> plugin.ProviderDescriptor.OutputSchemasEntry
	10, // 3: plugin.Schema.parameters:type_name -> plugin.Schema.ParametersEntry
	5,  // 4: plugin.ProviderDescriptor.OutputSchemasEntry.value:type_name -> plugin.Schema
	6,  // 5: plugin.Schema.ParametersEntry.value:type_name -> plugin.Parameter
	0,  // 6: plugin.PluginService.GetProviders:input_type -> plugin.GetProvidersRequest
	2,  // 7: plugin.PluginService.GetProviderDescriptor:input_type -> plugin.GetProviderDescriptorRequest
	7,  // 8: plugin.PluginService.ExecuteProvider:input_type -> plugin.ExecuteProviderRequest
	1,  // 9: plugin.PluginService.GetProviders:output_type -> plugin.GetProvidersResponse
	3,  // 10: plugin.PluginService.GetProviderDescriptor:output_type -> plugin.GetProviderDescriptorResponse
	8,  // 11: plugin.PluginService.ExecuteProvider:output_type -> plugin.ExecuteProviderResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_plugin_proto_plugin_proto_init() }
func file_pkg_plugin_proto_plugin_proto_init() {
	if File_pkg_plugin_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_proto_rawDesc), len(file_pkg_plugin_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugin_proto_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_plugin_proto_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_plugin_proto_plugin_proto_msgTypes,
	}.Build()
	File_pkg_plugin_proto_plugin_proto = out.File
	file_pkg_plugin_proto_plugin_proto_goTypes = nil
	file_pkg_plugin_proto_plugin_proto_depIdxs = nil
}
