// Copyright 2025-2026 Oakwood Commons
// SPDX-License-Identifier: Apache-2.0

package bundler

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

const (
	// LockFileVersion is the current lock file format version.
	LockFileVersion = 1

	// DefaultLockFileName is the default lock file name.
	DefaultLockFileName = "solution.lock"
)

// LockFile represents the lock file that records vendored dependency state.
// It enables reproducible builds by replaying exact versions and digests.
type LockFile struct {
	// Version is the lock file format version.
	Version int `json:"version" yaml:"version" doc:"Lock file format version" example:"1"`

	// Dependencies lists vendored solution dependencies with their digests.
	Dependencies []LockDependency `json:"dependencies,omitempty" yaml:"dependencies,omitempty" doc:"Vendored solution dependencies" maxItems:"1000"`

	// Plugins lists vendored plugin dependencies with their digests.
	Plugins []LockPlugin `json:"plugins,omitempty" yaml:"plugins,omitempty" doc:"Vendored plugin dependencies" maxItems:"100"`
}

// LockDependency records metadata about a vendored catalog dependency.
type LockDependency struct {
	// Ref is the original catalog reference (e.g., "deploy-to-k8s@2.0.0").
	Ref string `json:"ref" yaml:"ref" doc:"Original catalog reference" maxLength:"255" example:"deploy-to-k8s@2.0.0"`

	// Digest is the SHA-256 content digest of the vendored file.
	Digest string `json:"digest" yaml:"digest" doc:"SHA-256 content digest" maxLength:"128" example:"sha256:abc123..."`

	// ResolvedFrom is the catalog name from which the dependency was fetched.
	ResolvedFrom string `json:"resolvedFrom" yaml:"resolvedFrom" doc:"Source catalog name" maxLength:"255" example:"company-catalog"`

	// VendoredAt is the path relative to the bundle root where the file is stored.
	VendoredAt string `json:"vendoredAt" yaml:"vendoredAt" doc:"Relative path to vendored file" maxLength:"500" example:".scafctl/vendor/deploy-to-k8s@2.0.0.yaml"`
}

// LockPlugin records metadata about a vendored plugin dependency.
type LockPlugin struct {
	// Name is the plugin name.
	Name string `json:"name" yaml:"name" doc:"Plugin name" maxLength:"100" example:"azure-provider"`

	// Kind is the plugin kind (e.g., "provider", "auth-handler").
	Kind string `json:"kind" yaml:"kind" doc:"Plugin kind" maxLength:"50" example:"provider"`

	// Version is the resolved version string.
	Version string `json:"version" yaml:"version" doc:"Resolved version" maxLength:"50" example:"1.2.3"`

	// Digest is the SHA-256 content digest.
	Digest string `json:"digest" yaml:"digest" doc:"SHA-256 content digest" maxLength:"128" example:"sha256:abc123..."`

	// ResolvedFrom is the source registry or catalog.
	ResolvedFrom string `json:"resolvedFrom" yaml:"resolvedFrom" doc:"Source registry or catalog" maxLength:"255" example:"plugins.example.com"`
}

// FindDependency returns the lock entry for the given ref, or nil if not found.
func (lf *LockFile) FindDependency(ref string) *LockDependency {
	if lf == nil {
		return nil
	}
	for i := range lf.Dependencies {
		if lf.Dependencies[i].Ref == ref {
			return &lf.Dependencies[i]
		}
	}
	return nil
}

// FindPlugin returns the lock entry for a plugin by name and kind, or nil if not found.
func (lf *LockFile) FindPlugin(name, kind string) *LockPlugin {
	if lf == nil {
		return nil
	}
	for i := range lf.Plugins {
		if lf.Plugins[i].Name == name && lf.Plugins[i].Kind == kind {
			return &lf.Plugins[i]
		}
	}
	return nil
}

// LoadLockFile reads and parses a lock file from the given path.
// Returns nil without error if the file does not exist.
func LoadLockFile(path string) (*LockFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading lock file: %w", err)
	}

	var lf LockFile
	if err := yaml.Unmarshal(data, &lf); err != nil {
		return nil, fmt.Errorf("parsing lock file: %w", err)
	}

	if lf.Version != LockFileVersion {
		return nil, fmt.Errorf("unsupported lock file version %d (expected %d)", lf.Version, LockFileVersion)
	}

	return &lf, nil
}

// WriteLockFile serializes and writes the lock file to the given path.
func WriteLockFile(path string, lf *LockFile) error {
	if lf == nil {
		return fmt.Errorf("lock file is nil")
	}

	lf.Version = LockFileVersion

	data, err := yaml.Marshal(lf)
	if err != nil {
		return fmt.Errorf("serializing lock file: %w", err)
	}

	// Prepend a header comment
	header := []byte("# This file is auto-generated by scafctl build. Do not edit.\n")
	header = append(header, data...)

	if err := os.WriteFile(path, header, 0o600); err != nil {
		return fmt.Errorf("writing lock file: %w", err)
	}

	return nil
}
